### ISSUE TITLE
Customizing styles in line with current application

### ISSUE THREAD

**Issue by ohboyd** [pixielabs/balrog#5]
Hey, just added this to one of my apps, and I'm curious if there's a better way to customize it in my application. I'm currently going to try to just override the styles you've used in balrog/app/assets/stylesheets/balrog/gate.css, but I'm curious if you'd be able to add a type of class to the entire form, so I could easily override those tags without having application-wide changes to every section tag, button, footer, etc. I'm willing to submit a PR, for this thing, if there's interest in it.

It also could be useful to just drop the styles, altogether, so balrog just takes on the styles that we're using in our application already for sections, buttons, etc. Thanks for reading!

**Comment by JonathanAndrews** [comment]
Hello @ohboyd,

Currently there is no way to customise the Balrog Gate page. However it is definitely on the list of things we want to add to Balrog! We don't have an ETA for that, and please feel free to submit a PR

p.s. Excellent username. 👍

**Comment by ohboyd** [comment]
Hey! Thanks for the response. I'm in the middle of a few projects at the moment, but I'll play with the code when I have a bit more time, and I'll try to find a way to make it customizable. Do you have a preference between removing the styles altogether or adding specific classes/ids to each part? I think the perfect solution would be one that creates your custom stylesheet in app/stylesheets when you run a separate command (similar to how Rspec generates files when you run `rails generate rspec:install`). That would allow the user to choose if they want to have those styles, or if they'd prefer to inherit from their current stylesheets/bootstrap. 

A low tech alternative solution could be adding the particular stylesheets to the documentation, and giving the user instructions on how to create a new stylesheet and adding them to the project.

**Comment by JonathanAndrews** [comment]
We want there to be a default stylesheet so that people can just drop Balrog in and everything should “just work”. 

If people want to customise their own Balrog gate page then maybe we could have a generator that creates a view file in the dev’s app.

It could be similar to the way devise provides the `rails generate devise:views` command for users that want to customise their devise views.

**Comment by JonathanAndrews** [comment]
Implemented in #13
