### ISSUE TITLE
Issue with page navigation 

### ISSUE THREAD

**Issue by ohboyd** [pixielabs/balrog#6]
Sorry to add another issue, but I just realized that I can't go back from an edit action without freezing the page. It will take me to the balrog sign-in page, and then, if I return to the previous page, nothing is accessible. I'm using safari 12.1 on macOS Mojave (10.14.5)

**Comment by JonathanAndrews** [comment]
Hi again, thanks for raising an issue.

Hmm...not quite sure what you mean by nothing is accessible. 
Could you provide a step by step guide to replicate the bug or a sample app so we can look into it?

**Comment by ohboyd** [comment]
If I select an option that requires authentication, I'm taken to the page that has the balrog credentials. If I navigate back to the previous page without entering any credentials, I can't do anything on the page (select other options, fill out inputs, etc.). If I reload, the balrog box reloads, and I have to enter credentials, or close the tab and return to the page another way. It's happening on safari 12.1 on Mac running Mojave 10.14

**Comment by ohboyd** [comment]
Let me know if that's still not detailed enough, and I can provide more details.

**Comment by jalada** [comment]
Huh, that's really interesting. We might need an example app - that sounds like Balrog is interacting weirdly with Turbolinks or something like that. There's no reason why pressing back from Balrog should break the previous page you were on.

Does the back button work in your app in general? e.g. on that page, if you click to visit another page that isn't Balrog & then press back, it works OK?

**Comment by JonathanAndrews** [comment]
I'm closing this issue for now, but please re-open if you're able to re-create the bug.
